package com.example.domain

object StringsManager {
    fun getString(key: String, isSwahili: Boolean = true): String {
        return if (isSwahili) swahiliStrings[key] ?: key else englishStrings[key] ?: key
    }

    private val swahiliStrings = mapOf(
        "app_name" to "MSAADA",
        "tagline" to "Zana Rahisi. Kazi Rahisi. Maisha Rahisi.",
        "nav_home" to "Nyumbani",
        "nav_categories" to "Jamii",
        "nav_favorites" to "Vipendwa",
        "nav_settings" to "Mipangilio",
        "greeting" to "Karibu MSAADA",
        "search_hint" to "Unatafuta nini?",
        "search_full_hint" to "Tafuta unachohitaji…",
        "quick_tools" to "Vifaa vya Haraka",
        "categories" to "Kategoria",
        "view_all" to "Tazama zote",
        "recently_used" to "Zilizotumika Hivi Karibuni",
        "no_recents" to "Bado hujatumia zana yoyote hivi karibuni.",
        "no_favorites" to "Bado hujaongeza zana kwenye vipendwa.",
        "explore_tools" to "Gundua zana mbalimbali na uziweke hapa kwa urahisi.",
        "pro_badge" to "PRO",
        "get_pro" to "Pata MSAADA PRO",
        "later" to "Baadaye",
        "save" to "Hifadhi",
        "share" to "Shiriki",
        "download_pdf" to "Pakua PDF",
        "edit" to "Hariri",
        "delete" to "Futa",
        "clear" to "Safisha",
        "calculate" to "Hesabu",
        "calculate_again" to "Hesabu Tena",
        "estimate_disclaimer" to "Hesabu hizi ni makadirio tu.",
        "total" to "Jumla",
        "subtotal" to "Jumla Ndogo",
        "tax" to "Kodi (VAT 18%)",
        "discount" to "Punguzo",
        "currency_tsh" to "TSh",
        "settings_lang" to "Lugha",
        "settings_theme" to "Mandhari",
        "settings_notifications" to "Arifa",
        "settings_clear_data" to "Futa Data ya Ndani",
        "settings_about" to "Kuhusu MSAADA",
        "settings_version" to "Toleo",
        "onboarding_1_title" to "Karibu MSAADA",
        "onboarding_1_desc" to "Zana rahisi za kukusaidia kwenye kazi za kila siku.",
        "onboarding_2_title" to "Fanya Kazi kwa Urahisi",
        "onboarding_2_desc" to "Pata calculators, planners, business tools na zana nyingine sehemu moja.",
        "onboarding_3_title" to "Unda Kitaalamu",
        "onboarding_3_desc" to "Tengeneza documents nzuri na professional templates kwa urahisi.",
        "continue" to "Endelea",
        "skip" to "Ruka",
        "start" to "Anza Kutumia"
    )

    private val englishStrings = mapOf(
        "app_name" to "MSAADA",
        "tagline" to "Simple Tools. Easy Work. Simple Life.",
        "nav_home" to "Home",
        "nav_categories" to "Categories",
        "nav_favorites" to "Favorites",
        "nav_settings" to "Settings",
        "greeting" to "Welcome to MSAADA",
        "search_hint" to "What are you looking for?",
        "search_full_hint" to "Search for what you need…",
        "quick_tools" to "Quick Tools",
        "categories" to "Categories",
        "view_all" to "View all",
        "recently_used" to "Recently Used",
        "no_recents" to "You haven't used any tools recently.",
        "no_favorites" to "No favorite tools added yet.",
        "explore_tools" to "Discover tools and add them to your favorites for quick access.",
        "pro_badge" to "PRO",
        "get_pro" to "Get MSAADA PRO",
        "later" to "Maybe Later",
        "save" to "Save",
        "share" to "Share",
        "download_pdf" to "Download PDF",
        "edit" to "Edit",
        "delete" to "Delete",
        "clear" to "Clear",
        "calculate" to "Calculate",
        "calculate_again" to "Recalculate",
        "estimate_disclaimer" to "These calculations are estimates only.",
        "total" to "Total",
        "subtotal" to "Subtotal",
        "tax" to "Tax (VAT 18%)",
        "discount" to "Discount",
        "currency_tsh" to "TZS",
        "settings_lang" to "Language",
        "settings_theme" to "Appearance",
        "settings_notifications" to "Notifications",
        "settings_clear_data" to "Clear Local Data",
        "settings_about" to "About MSAADA",
        "settings_version" to "Version",
        "onboarding_1_title" to "Welcome to MSAADA",
        "onboarding_1_desc" to "Simple everyday life utility tools right at your fingertips.",
        "onboarding_2_title" to "Work Effortlessly",
        "onboarding_2_desc" to "Access calculators, planners, business tools and everyday utilities in one place.",
        "onboarding_3_title" to "Create Professionally",
        "onboarding_3_desc" to "Generate beautiful documents and professional templates with ease.",
        "continue" to "Continue",
        "skip" to "Skip",
        "start" to "Get Started"
    )
}
